export interface StateTax {
  name: string;
  rate: number;
}

export const US_STATES: StateTax[] = [
  { name: "Alabama", rate: 9.29 },
  { name: "Alaska", rate: 1.82 },
  { name: "Arizona", rate: 8.38 },
  { name: "Arkansas", rate: 9.44 },
  { name: "California", rate: 8.85 },
  { name: "Colorado", rate: 7.81 },
  { name: "Connecticut", rate: 6.35 },
  { name: "Delaware", rate: 0.00 },
  { name: "Florida", rate: 7.02 },
  { name: "Georgia", rate: 7.38 },
  { name: "Hawaii", rate: 4.50 },
  { name: "Idaho", rate: 6.03 },
  { name: "Illinois", rate: 8.86 },
  { name: "Indiana", rate: 7.00 },
  { name: "Iowa", rate: 6.94 },
  { name: "Kansas", rate: 8.75 },
  { name: "Kentucky", rate: 6.00 },
  { name: "Louisiana", rate: 9.56 },
  { name: "Maine", rate: 5.50 },
  { name: "Maryland", rate: 6.00 },
  { name: "Massachusetts", rate: 6.25 },
  { name: "Michigan", rate: 6.00 },
  { name: "Minnesota", rate: 7.52 },
  { name: "Mississippi", rate: 7.06 },
  { name: "Missouri", rate: 8.39 },
  { name: "Montana", rate: 0.00 },
  { name: "Nebraska", rate: 6.97 },
  { name: "Nevada", rate: 8.24 },
  { name: "New Hampshire", rate: 0.00 },
  { name: "New Jersey", rate: 6.60 },
  { name: "New Mexico", rate: 7.62 },
  { name: "New York", rate: 8.53 },
  { name: "North Carolina", rate: 7.00 },
  { name: "North Dakota", rate: 7.04 },
  { name: "Ohio", rate: 7.24 },
  { name: "Oklahoma", rate: 8.99 },
  { name: "Oregon", rate: 0.00 },
  { name: "Pennsylvania", rate: 6.34 },
  { name: "Rhode Island", rate: 7.00 },
  { name: "South Carolina", rate: 7.50 },
  { name: "South Dakota", rate: 6.11 },
  { name: "Tennessee", rate: 9.55 },
  { name: "Texas", rate: 8.20 },
  { name: "Utah", rate: 7.25 },
  { name: "Vermont", rate: 6.30 },
  { name: "Virginia", rate: 5.77 },
  { name: "Washington", rate: 9.40 },
  { name: "West Virginia", rate: 6.57 },
  { name: "Wisconsin", rate: 5.43 },
  { name: "Wyoming", rate: 5.44 },
  { name: "District of Columbia", rate: 6.00 }
].sort((a, b) => a.name.localeCompare(b.name));
